// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3sB0KT-yFv2cR7EmGknxTyxu_uyd4_P4',
    appId: '1:721239793207:web:54eeb902754d4769e3a9b2',
    messagingSenderId: '721239793207',
    projectId: 'animal-health-d4d0d',
    authDomain: 'animal-health-d4d0d.firebaseapp.com',
    storageBucket: 'animal-health-d4d0d.firebasestorage.app',
    measurementId: 'G-Q4P3RSPNW0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmYfIaPPuRZUrate1GgHJIZEBgFAG89yk',
    appId: '1:721239793207:android:4b0a3ea8e9851179e3a9b2',
    messagingSenderId: '721239793207',
    projectId: 'animal-health-d4d0d',
    storageBucket: 'animal-health-d4d0d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLu7KQ0bq6I035gOYJqNpwMOxJ04YomGo',
    appId: '1:721239793207:ios:1901fe840fa0028ae3a9b2',
    messagingSenderId: '721239793207',
    projectId: 'animal-health-d4d0d',
    storageBucket: 'animal-health-d4d0d.firebasestorage.app',
    iosBundleId: 'com.MouseInc.animalHealth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLu7KQ0bq6I035gOYJqNpwMOxJ04YomGo',
    appId: '1:721239793207:ios:1901fe840fa0028ae3a9b2',
    messagingSenderId: '721239793207',
    projectId: 'animal-health-d4d0d',
    storageBucket: 'animal-health-d4d0d.firebasestorage.app',
    iosBundleId: 'com.MouseInc.animalHealth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3sB0KT-yFv2cR7EmGknxTyxu_uyd4_P4',
    appId: '1:721239793207:web:ac9bc73e657071c5e3a9b2',
    messagingSenderId: '721239793207',
    projectId: 'animal-health-d4d0d',
    authDomain: 'animal-health-d4d0d.firebaseapp.com',
    storageBucket: 'animal-health-d4d0d.firebasestorage.app',
    measurementId: 'G-K82Z4G22V0',
  );
}
